Like-Lion-Team-WAY/WAY

build.gradle, src/main/resources/application.properties, src/main/resources/application.yml, src/main/resources/static/css/main.css, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/fragments/header.html, src/main/resources/templates/layouts/layout.html, src/main/resources/templates/pages/user/test.html
=> [Feature] thymeleaf layout fragments 

src/main/java/like/lion/way/user/domain/User.java, src/main/java/like/lion/way/user/repository/UserRepository.java, src/main/java/like/lion/way/user/service/UserService.java
=> [Feature] user entity domain

build.gradle, src/main/java/like/lion/way/board/api/BoardController.java, src/main/java/like/lion/way/board/api/request/BoardCreateRequest.java, src/main/java/like/lion/way/board/api/request/BoardEditRequest.java, src/main/java/like/lion/way/board/application/BoardService.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/request/BoardCreateServiceRequest.java, src/main/java/like/lion/way/board/application/request/BoardEditServiceRequest.java, src/main/java/like/lion/way/board/domain/AnonymousPermission.java, src/main/java/like/lion/way/board/domain/Board.java, src/main/java/like/lion/way/board/domain/BoardPost.java, src/main/java/like/lion/way/user/repository/UserRepository.java
close #22 
게시판에 필요한 crud api 구현했습니다.
- BoardController
- BoardService
프론트 요소는 따로 이슈 파서 작업하겠습니다.
AnonymousPermission은 나중에 익명 허용 처리할 때 수정하겠습니다!
build.gradle 의존성 변경사항 확인 한 번 해주세요!
=> [Feature] implement crud api about community board

src/main/java/like/lion/way/board/api/request/BoardEditRequest.java, src/main/java/like/lion/way/config/SecurityConfig.java, src/main/java/like/lion/way/user/domain/User.java, src/main/java/like/lion/way/user/oauth2/dto/OAuthAttributes.java, src/main/java/like/lion/way/user/oauth2/handler/CustomOAuth2SuccessHandler.java, src/main/java/like/lion/way/user/oauth2/service/CustomOAuth2UserService.java, src/main/java/like/lion/way/user/repository/UserRepository.java, src/main/java/like/lion/way/user/service/UserService.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java
구글 네이버 OAuth2 , security permitAll update
=> [Feature] OAuth2 naver google #29 Open

build.gradle, src/main/java/like/lion/way/chat/controller/ChatController.java, src/main/java/like/lion/way/chat/controller/MessageController.java, src/main/java/like/lion/way/chat/controller/WebSocketController.java, src/main/java/like/lion/way/chat/domain/Chat.java, src/main/java/like/lion/way/chat/domain/Message.java, src/main/java/like/lion/way/chat/repository/MessageRepository.java, src/main/java/like/lion/way/chat/service/MessageService.java, src/main/java/like/lion/way/chat/service/impl/MessageServiceImpl.java, src/main/java/like/lion/way/chat/service/kafka/Consumer.java, src/main/java/like/lion/way/chat/service/kafka/Imple/ConsumerImpl.java, src/main/java/like/lion/way/chat/service/kafka/Imple/ProducerImpl.java, src/main/java/like/lion/way/chat/service/kafka/Producer.java, src/main/java/like/lion/way/chat/service/kafka/imple/ConsumerImpl.java, src/main/java/like/lion/way/chat/service/kafka/imple/ProducerImpl.java, src/main/java/like/lion/way/config/KafkaConfig.java, src/main/java/like/lion/way/config/WebSocketConfig.java, src/main/resources/static/css/chat/chat-room.css, src/main/resources/static/css/chat/chat.css, src/main/resources/static/js/chat/chat-room.js, src/main/resources/static/js/chat/chat.js, src/main/resources/templates/pages/chat/chat-room.html, src/main/resources/templates/pages/chat/chats.html
채팅방 메세징 기본 구현
- kafka(producer, consumer) 이용한 메세징
- message 데이터 저장할 mongo 설정
- 임시 채팅 리스트 페이지 및 임시 채팅방 페이지 구현
- 채팅방 : 이전 대화 불러와서 보여주기 O
- 채팅방 : 해당 채팅방 끼리만 메시지 주고 받기 O
- 채팅 리스트 : 실시간으로 주고받은 마지막 메세지 업데이트 O
close #30
=> [Feature] basic chatting implement

src/main/java/like/lion/way/board/api/BoardController.java, src/main/java/like/lion/way/board/api/BoardRestController.java, src/main/java/like/lion/way/board/application/BoardService.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/response/BoardPostResponse.java, src/main/java/like/lion/way/chat/controller/ChatController.java, src/main/resources/static/css/boards/boardSetting.css, src/main/resources/static/js/boards/boardCreate.js, src/main/resources/static/js/boards/boardSetting.js, src/main/resources/static/js/boards/post.js, src/main/resources/templates/fragments/header.html, src/main/resources/templates/pages/boards/boardSettingForm.html
close #43 
게시판 수정, 삭제 기능 구현했습니다.
---
추가로,
header.html 커뮤니티에 api 연결했습니다.
게시글 제목 깨지는 거 수정했습니다.
아까 시연 때 페이지 안 넘어가졌던 거는 board_posts에 user_id가 null인 데이터가 있어서 그랬던 거였습니다.
---
Controller : 게시판 수정, 게시글 목록, 게시글 생성, 게시글 상세 페이지
RestController : 게시판 수정, 게시판 삭제, 게시글 정보 요청, 게시글 생성
api 변경돼서 노션에 업데이트 했습니다. 혹시 놓친 부분이 있을 수 있으니 확인 한 번 해주시면 감사하겠습니다...!
=> [Feature] implement board update and delete

build.gradle, src/main/java/like/lion/way/config/ElasticSearchConfig.java, src/main/java/like/lion/way/els/controller/ElsInterestRestController.java, src/main/java/like/lion/way/els/domain/ElsInterest.java, src/main/java/like/lion/way/els/repository/ElsInterestRepository.java, src/main/java/like/lion/way/els/service/ElsInterestService.java, src/main/java/like/lion/way/els/service/serviceimpl/ElsInterestServiceImpl.java, src/main/java/like/lion/way/user/controller/InterestController.java, src/main/java/like/lion/way/user/controller/restcontroller/InterestRestController.java, src/main/java/like/lion/way/user/controller/restcontroller/UserRestController.java, src/main/java/like/lion/way/user/domain/Interest.java, src/main/java/like/lion/way/user/domain/User.java, src/main/java/like/lion/way/user/repository/InterestRepository.java, src/main/java/like/lion/way/user/service/InterestService.java, src/main/java/like/lion/way/user/service/UserService.java, src/main/java/like/lion/way/user/service/serviceImpl/InterestServiceImpl.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java, src/main/resources/templates/pages/user/like.html
=> feat: elasticsearch , interest feature

src/main/java/like/lion/way/alarm/controller/AlarmController.java, src/main/java/like/lion/way/alarm/controller/AlarmRestController.java, src/main/java/like/lion/way/alarm/controller/SseRestController.java, src/main/java/like/lion/way/alarm/event/AlarmEventListener.java, src/main/java/like/lion/way/alarm/service/AlarmSseEmitters.java, src/main/java/like/lion/way/alarm/service/serviceImpl/AlarmSseEmittersImpl.java, src/main/resources/static/js/header.js, src/main/resources/templates/fragments/header.html, src/main/resources/templates/pages/alarm/alarm.html
- 알람 예외, 에러 뜨던거 수정
- 여러 개의 창에서 알림 받도록 수정
=> [Feature] fix alarm exception

src/main/java/like/lion/way/board/api/BoardRestController.java, src/main/java/like/lion/way/board/api/request/BoardPostCommentRequest.java, src/main/java/like/lion/way/board/application/BoardService.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/request/BoardPostCommentServiceRequest.java, src/main/java/like/lion/way/board/application/response/BoardPostCommentCountResponse.java, src/main/java/like/lion/way/board/application/response/BoardPostCommentResponse.java, src/main/java/like/lion/way/board/application/response/BoardPostDetailResponse.java, src/main/java/like/lion/way/board/domain/BoardPostComment.java, src/main/java/like/lion/way/board/repository/BoardPostCommentRepository.java, src/main/java/like/lion/way/board/repository/BoardPostScrapRepository.java, src/main/resources/static/js/boards/postDetail.js, src/main/resources/templates/pages/boards/postDetailForm.html
close #61 
게시글 댓글 및 대댓글 구현했습니다.
게시글 상세보기 페이지 구현했습니다.
RestController '게시글 상세보기', '게시글 댓글' api 주소 변경되어서 노션에 업데이트 했습니다.
게시글 상세보기 페이지 CSS는 나중에 처리하겠습니다...지금은 좀 안 예뻐요 😭
=> [Feature] implement Board Post Comment

src/main/java/like/lion/way/jwt/exception/CustomAuthenticationEntryPoint.java, src/main/resources/static/css/boards/board.css, src/main/resources/static/js/common.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/fragments/header.html, src/main/resources/templates/layouts/layout.html, src/main/resources/templates/pages/boards/boardForm.html
-커뮤니티 , 질문 클릭 시 aside view change 구현
=> feat: header , aside view change

src/main/java/like/lion/way/jwt/util/JwtUtil.java, src/main/java/like/lion/way/user/controller/FollowController.java, src/main/java/like/lion/way/user/service/FollowService.java, src/main/java/like/lion/way/user/service/serviceImpl/FollowServiceImpl.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java, src/main/resources/static/js/common.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/fragments/header.html
=> Feature/71 no login aside view 

src/main/java/like/lion/way/chat/controller/ChatController.java, src/main/java/like/lion/way/chat/controller/rest/ChatRestController.java, src/main/java/like/lion/way/chat/controller/rest/MessageRestController.java, src/main/java/like/lion/way/chat/domain/Chat.java, src/main/java/like/lion/way/chat/domain/Message.java, src/main/java/like/lion/way/chat/domain/dto/ChatInfoDTO.java, src/main/java/like/lion/way/chat/domain/dto/ChatRoomViewDTO.java, src/main/java/like/lion/way/chat/domain/dto/ReceiveMessageDTO.java, src/main/java/like/lion/way/chat/repository/ChatRepository.java, src/main/java/like/lion/way/chat/repository/MessageRepository.java, src/main/java/like/lion/way/chat/service/ChatService.java, src/main/java/like/lion/way/chat/service/MessageService.java, src/main/java/like/lion/way/chat/service/impl/ChatServiceImpl.java, src/main/java/like/lion/way/chat/service/impl/MessageServiceImpl.java, src/main/java/like/lion/way/chat/service/kafka/imple/ConsumerImpl.java, src/main/java/like/lion/way/chat/service/kafka/imple/ProducerImpl.java, src/main/resources/static/css/chat/chat-room.css, src/main/resources/static/css/chat/chat.css, src/main/resources/static/js/chat/chat-room.js, src/main/resources/static/js/chat/chat.js, src/main/resources/templates/pages/chat/chat-room.html
- 익명 기능 추가
-  상대 나갈때 및 익명 허용시 ui 변경되도록 수정
- 읽음 상태 확인 기능 추가
close #60
=> [Feature] chatting func with question and user 2

src/main/java/like/lion/way/alarm/controller/AlarmController.java, src/main/java/like/lion/way/alarm/controller/AlarmRestController.java, src/main/java/like/lion/way/alarm/domain/Alarm.java, src/main/java/like/lion/way/alarm/domain/AlarmSetting.java, src/main/java/like/lion/way/alarm/domain/AlarmType.java, src/main/java/like/lion/way/alarm/dto/AlarmMessageDto.java, src/main/java/like/lion/way/alarm/dto/AlarmRequestDto.java, src/main/java/like/lion/way/alarm/event/AlarmEventListener.java, src/main/java/like/lion/way/alarm/repository/AlarmRepository.java, src/main/java/like/lion/way/alarm/repository/AlarmSettingRepository.java, src/main/java/like/lion/way/alarm/service/AlarmService.java, src/main/java/like/lion/way/alarm/service/AlarmSseEmitters.java, src/main/java/like/lion/way/alarm/service/serviceImpl/AlarmServiceImpl.java, src/main/java/like/lion/way/alarm/service/serviceImpl/AlarmSseEmittersImpl.java, src/main/java/like/lion/way/feed/service/imp/PostCommentServiceImpl.java, src/main/java/like/lion/way/feed/service/imp/QuestionServiceImpl.java, src/main/resources/static/css/alarm/alarm.css, src/main/resources/static/css/alarm/alarmSetting.css, src/main/resources/static/js/alarm/alarm.js, src/main/resources/static/js/alarm/alarmSetting.js, src/main/resources/static/js/header.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/pages/alarm/alarm.html, src/main/resources/templates/pages/alarm/alarmSetting.html
close #58
- 알림 리스트 화면, 해당 화면에서 sse 수신
- 알림 설정 화면
- 알림 이벤트 적용 (새질문, 답변, 댓글, 대댓글)
=> [Feature] alarm service and controller

src/main/java/like/lion/way/chat/service/kafka/imple/ConsumerImpl.java
- 나가기시 에러 수정
- message 타입 close로 참여유저 리스트 null 되어 에러 발생
- null 확인 부분 추가
=> [Fix] Chat leave error

src/main/java/like/lion/way/board/api/BoardController.java, src/main/java/like/lion/way/board/api/BoardRestController.java, src/main/java/like/lion/way/board/application/BoardService.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/response/BoardPostScrapsResponse.java, src/main/java/like/lion/way/board/repository/BoardPostScrapRepository.java, src/main/resources/static/css/boards/scrap.css, src/main/resources/static/js/boards/scrap.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/pages/boards/scrapForm.html
close #74 
스크랩 게시글 로직 및 페이지 구현했습니다.
추가로 aside에 스크랩 url 연결했습니다.
=> [Feature] implement scraped board posts

src/main/resources/static/js/chat/chat.js, src/main/resources/static/js/feed/userFeed.js, src/main/resources/templates/pages/chat/chats.html, src/main/resources/templates/pages/feed/userFeed.html
=> [Feature] create Chat from Question page

src/main/java/like/lion/way/user/controller/restcontroller/FollowRestController.java, src/main/java/like/lion/way/user/repository/FollowRepository.java, src/main/java/like/lion/way/user/service/FollowService.java, src/main/java/like/lion/way/user/service/serviceImpl/FollowServiceImpl.java
=> [feature] no-login aside view

src/main/resources/static/css/boards/postDetail.css, src/main/resources/static/js/boards/postDetail.js
=> [Html&css] board_post detail page design

src/main/resources/static/css/boards/board.css, src/main/resources/static/css/boards/boardCreate.css, src/main/resources/static/css/boards/boardSetting.css, src/main/resources/static/css/boards/post.css, src/main/resources/static/css/boards/postCreate.css, src/main/resources/static/css/boards/scrap.css, src/main/resources/static/js/boards/post.js, src/main/resources/static/js/boards/scrap.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/pages/boards/boardCreateForm.html, src/main/resources/templates/pages/boards/boardForm.html, src/main/resources/templates/pages/boards/boardSettingForm.html, src/main/resources/templates/pages/boards/postCreateForm.html, src/main/resources/templates/pages/boards/postDetailForm.html, src/main/resources/templates/pages/boards/postForm.html, src/main/resources/templates/pages/boards/scrapForm.html
💡 연관된 이슈
close #83 
📝 작업 내용
-  게시판 목록
-  게시판 세팅
-  게시글 목록
-  게시글 작성
-  게시글 상세보기
-  스크랩 게시글
css 적용했습니다. (html title도 수정했습니다.)
게시글 상세보기는 나연님이 해주셨습니다.
💬 리뷰 요구 사항
=> [Html&css] improve community css style

src/main/java/like/lion/way/common/controller/CommonController.java, src/main/java/like/lion/way/config/SecurityConfig.java, src/main/java/like/lion/way/user/controller/UserController.java, src/main/java/like/lion/way/user/service/UserService.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java, src/main/resources/static/js/common.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/pages/common/main.html, src/main/resources/templates/pages/user/followSetting.html, src/main/resources/templates/pages/user/like.html, src/main/resources/templates/pages/user/login.html, src/main/resources/templates/pages/user/loginInfo.html
- 로그아웃
- html title수정
- local storage set 
- security authentication
=> [Feature] logout

src/main/java/like/lion/way/chat/controller/rest/ChatRestController.java, src/main/resources/static/css/chat/chat-room.css, src/main/resources/static/css/chat/chat.css, src/main/resources/static/js/chat/chat-room.js, src/main/resources/static/js/feed/userFeed.js, src/main/resources/templates/pages/chat/chat-room.html, src/main/resources/templates/pages/chat/chats.html
- 화면 ui 약간 수정
- 비회원의 질문으로부터 채팅 생성 막기
close #98
=> [Feature] chatting part 1st check

src/main/java/like/lion/way/admin/service/Impl/ReportServiceImpl.java, src/main/resources/static/css/feed/questionPage.css, src/main/resources/static/js/feed/commentEdit.js, src/main/resources/static/js/feed/postEdit.js, src/main/resources/static/js/feed/report_question.js, src/main/resources/templates/pages/feed/detailFeed.html, src/main/resources/templates/pages/feed/rejectedQuestionPage.html
=> [Feature] report

src/main/java/like/lion/way/feed/controller/ArchieveController.java, src/main/java/like/lion/way/feed/controller/Post2Controller.java, src/main/java/like/lion/way/feed/controller/QuestionBoxController.java, src/main/java/like/lion/way/feed/controller/QuestionFilterController.java, src/main/java/like/lion/way/feed/domain/Post.java, src/main/java/like/lion/way/feed/domain/PostComment.java, src/main/resources/static/css/common/main.css, src/main/resources/templates/pages/feed/archievePage.html, src/main/resources/templates/pages/feed/questionPage.html, src/main/resources/templates/pages/feed/sendQuestion.html, src/main/resources/templates/pages/feed/userFeed.html
close #100 
- 보관함 
보관함 취소
- userFeed 의 피드 게시글의 img 필터
- 게시글 상세 보기의 comment 오름차순 정렬
=> [Feature] implement postbox questionbox cancel

build.gradle, src/main/java/like/lion/way/config/S3Config.java, src/main/java/like/lion/way/config/SecurityConfig.java, src/main/java/like/lion/way/feed/controller/Post2Controller.java, src/main/java/like/lion/way/file/controller/FileRestController.java, src/main/java/like/lion/way/file/service/S3Service.java, src/main/java/like/lion/way/file/service/impl/S3ServiceImpl.java, src/main/java/like/lion/way/user/controller/restcontroller/UserRestController.java, src/main/resources/static/css/main.css, src/test/java/like/lion/way/S3test.http
=> setting: s3 bucket Setting

build.gradle, src/main/java/like/lion/way/common/controller/CommonController.java, src/main/java/like/lion/way/feed/controller/ArchieveController.java, src/main/java/like/lion/way/feed/controller/Post2Controller.java, src/main/java/like/lion/way/feed/controller/PostController.java, src/main/java/like/lion/way/feed/controller/QuestionController.java, src/main/java/like/lion/way/feed/service/PostService.java, src/main/java/like/lion/way/feed/service/QuestionService.java, src/main/java/like/lion/way/feed/service/imp/PostServiceImpl.java, src/main/java/like/lion/way/feed/service/imp/QuestionServiceImpl.java, src/main/resources/templates/pages/common/main.html, src/main/resources/templates/pages/feed/userFeed.html
- main 
팔로우 한 사람들의 질문과 게시글이 뜨게 했습니다.
질문 받은 사용자(내가 팔로우 하는 사용자)의 링크도 연결해줬습니다.
- question
- feed
게시글과 질문 작성시, s3에 이미지 저장이 되도록 수정했습니다.
- userFeed 
사용자의 id 명 대신 nickname 이 보이도록 수정했습니다.
혹시 궁금하신 부분이 있으시다면 답변 남겨주세요!!😎👌
close #110
=> [Feature] post & question image upload, main filter and userFeed name change

src/main/java/like/lion/way/common/controller/CommonController.java, src/main/java/like/lion/way/feed/controller/Post2Controller.java, src/main/java/like/lion/way/feed/controller/PostRestController.java, src/main/java/like/lion/way/feed/controller/Question2Controller.java, src/main/java/like/lion/way/feed/controller/QuestionController.java, src/main/java/like/lion/way/feed/controller/QuestionFilterController.java, src/main/java/like/lion/way/file/service/S3Service.java, src/main/java/like/lion/way/file/service/impl/S3ServiceImpl.java
- main
링크 경로 잘못 설정해서 수정했습니다!
- question & post (==feed)
질문이랑 게시글 삭제시 이미지가 있다면 mysql 에서 삭제 전에 s3 에서 먼저 삭제하도록 해놨습니다.
- file (s3)
s3ServiceImpl 에 삭제하는 코드도 추가했습니다.
<mark>혹시 코드에서 궁금하신 사항이 있으시면 댓글 남겨주세요!!😊👍😉</mark>
=> [Feature]  s3 image delete and edit question & post delete 

src/main/java/like/lion/way/user/controller/restcontroller/UserRestController.java, src/main/java/like/lion/way/user/service/serviceImpl/BlockServiceImpl.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java
=> [Feature] s3 bucket img delete

src/main/java/like/lion/way/admin/domain/Report.java, src/main/java/like/lion/way/admin/domain/ReportRequestDto.java, src/main/java/like/lion/way/admin/service/Impl/ReportServiceImpl.java, src/main/java/like/lion/way/chat/service/MessageService.java, src/main/java/like/lion/way/chat/service/impl/MessageServiceImpl.java, src/main/resources/static/css/chat/chat-room.css, src/main/resources/static/js/chat/chat-room.js
=> [Feature] report chatting

src/main/java/like/lion/way/board/api/BoardController.java, src/main/java/like/lion/way/board/api/BoardRestController.java, src/main/java/like/lion/way/board/api/request/BoardPostEditRequest.java, src/main/java/like/lion/way/board/application/BoardService.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/request/BoardPostEditServiceRequest.java, src/main/java/like/lion/way/board/application/response/BoardPostDetailResponse.java, src/main/java/like/lion/way/board/application/response/BoardTitleResponse.java, src/main/java/like/lion/way/board/domain/BoardPost.java, src/main/resources/static/css/boards/post.css, src/main/resources/static/css/boards/postDetail.css, src/main/resources/static/js/boards/post.js, src/main/resources/static/js/boards/postDetail.js, src/main/resources/static/js/boards/postEdit.js, src/main/resources/templates/pages/boards/postDetailForm.html, src/main/resources/templates/pages/boards/postEditForm.html, src/main/resources/templates/pages/boards/postForm.html
close #115 
게시판, 게시글 생성자만 수정 및 삭제 가능하도록 구현했습니다.
=> [Feature] implement community settings

src/main/java/like/lion/way/chat/constant/ApiMessage.java, src/main/java/like/lion/way/chat/constant/ChatMessageType.java, src/main/java/like/lion/way/chat/constant/OpenNicknameState.java, src/main/java/like/lion/way/chat/controller/ChatController.java, src/main/java/like/lion/way/chat/controller/MessageController.java, src/main/java/like/lion/way/chat/controller/rest/ChatRestController.java, src/main/java/like/lion/way/chat/controller/rest/MessageRestController.java, src/main/java/like/lion/way/chat/domain/Chat.java, src/main/java/like/lion/way/chat/domain/dto/ChatInfoDTO.java, src/main/java/like/lion/way/chat/service/impl/ChatServiceImpl.java, src/main/java/like/lion/way/chat/service/impl/MessageServiceImpl.java, src/main/java/like/lion/way/chat/service/kafka/imple/ConsumerImpl.java, src/main/java/like/lion/way/chat/service/kafka/imple/ProducerImpl.java
1차 리팩토링 진행
- 상수 enum으로 변경
- 너무 긴 메서드 분리작업
close #121
=> [Refactor] refactoring chatting part

src/main/java/like/lion/way/config/SecurityConfig.java, src/main/java/like/lion/way/els/controller/ElsUserController.java, src/main/java/like/lion/way/els/controller/ElsUserRestController.java, src/main/java/like/lion/way/els/domain/ElsUser.java, src/main/java/like/lion/way/els/repository/ElsUserRepository.java, src/main/java/like/lion/way/els/service/ElsUserService.java, src/main/java/like/lion/way/els/service/serviceimpl/ElsUserServiceImpl.java, src/main/java/like/lion/way/feed/controller/PostController.java, src/main/java/like/lion/way/feed/controller/QuestionController.java, src/main/java/like/lion/way/feed/controller/ShareMypage.java, src/main/java/like/lion/way/feed/service/LikeService.java, src/main/java/like/lion/way/feed/service/PostBoxService.java, src/main/java/like/lion/way/feed/service/PostCommentService.java, src/main/java/like/lion/way/feed/service/PostService.java, src/main/java/like/lion/way/feed/service/QuestionBoxService.java, src/main/java/like/lion/way/feed/service/QuestionService.java, src/main/java/like/lion/way/feed/service/imp/QuestionServiceImpl.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java, src/main/resources/static/css/common/main.css, src/main/resources/static/css/feed/feed.css, src/main/resources/static/css/main.css, src/main/resources/static/css/user/userSearch.css, src/main/resources/static/js/user/userSearch.js, src/main/resources/templates/fragments/header.html, src/main/resources/templates/pages/common/main.html, src/main/resources/templates/pages/feed/shareMyPage.html, src/main/resources/templates/pages/feed/userFeed.html, src/main/resources/templates/pages/user/searchform.html
close #120 
- <mark>elasticsearch</mark>
<mark>첫 시도: </mark> username 으로만 
username 을 검색해서 한 글자라도 포함되면 username 이 뜨게 했습니다.
허전해 보여서 이미지 필드도 추가해서 이미지까지 보이게 구현했습니다.<br>
<mark>두 번째 시도:</mark>  tag+username
username 을 interests 필드를 하나 만들어서 username과 tag 를 리스트로 넣어서 그 interest 에서 검색을 할 수 있게 반영했습니다.<br>
회원가입 시, elasticSearch 에 회원가입 내용 따로 저장해주고, 탈퇴할 때 elasticsearch 에서도 같이 삭제되게 했습니다.
따로 정보 확인하고 싶으시면, /user/all 하시면 확인하실 수 있습니다.
- <mark>main css 수정</mark>
question 의 프로필 이미지 추가
익명이 아닌 사용자의 경우, 이름을 눌렀을 때 그 사람의 피드창으로 넘어가게 했습니다.
hover 를 각 div 마다 설정해줬습니다. 
- <mark>userfeed 질문 답변한 것만 필터링</mark>
질문 답변된 것만 필터링 처리를 하지 못 하고 있어서 필터링 처리 되도록 다시 수정했습니다.
- <mark>로그인 후 질문 작성시, 익명 실명 처리 안 되는 부분</mark>
s3 로 이미지 처리를 하면서 잘못 로직을 짜서 수정했습니다.
questionController 부분 확인하시면 됩니다!!
- <mark>카카오 공유</mark>
로그인한 사용자가 자기 피드에서 공유하기 버튼을 …
=> [Feature] elasticsearch & kakao share

src/main/java/like/lion/way/config/SecurityConfig.java, src/main/java/like/lion/way/user/controller/FollowController.java, src/main/java/like/lion/way/user/controller/UserController.java, src/main/java/like/lion/way/user/service/BlockService.java, src/main/java/like/lion/way/user/service/serviceImpl/BlockServiceImpl.java, src/main/java/like/lion/way/user/service/serviceImpl/FollowServiceImpl.java, src/main/resources/templates/pages/feed/userFeed.html, src/main/resources/templates/pages/user/followSetting.html
- 타유저일시,차단목록은 보여주지않도록 수정
- 타유저일 시 언팔로우 , 삭제버튼 안보이게
- 본인피드에서 클릭해도 삭제버튼 나오도록 구현
=> fix: 팔로워 팔로잉 타 유저 목록 보여주기

src/main/java/like/lion/way/chat/service/impl/MessageServiceImpl.java, src/main/java/like/lion/way/chat/service/kafka/imple/ConsumerImpl.java, src/main/resources/static/js/chat/chat-room.js, src/main/resources/templates/pages/chat/chat-room.html
- 채팅 알림 추가
- 사이드바 신고 버튼 삭제
close #128
=> [Feature] chatting alarm

src/main/java/like/lion/way/board/api/BoardController.java, src/main/java/like/lion/way/board/api/BoardRestController.java, src/main/java/like/lion/way/board/application/BoardService.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/response/BoardBestPostResponse.java, src/main/java/like/lion/way/board/repository/BoardPostRepository.java, src/main/resources/static/css/boards/bestPost.css, src/main/resources/static/js/boards/bestPost.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/pages/boards/bestPost.html
💡 연관된 이슈
close #131 
📝 작업 내용
- 베스트 게시글 로직 및 페이지 구현했습니다.
- 하루 기준 업데이트로 할까 고민하다가 베스트 게시판 확인할 때마다 업데이트 되게 했습니다.
- 좋아요 10개 이상 받으면 최대 10개까지 좋아요 많은 순으로 정렬됩니다.
@Cacheable 쓰면 성능을 확장시킬 수 있다 하는데, 나중에 디벨롭 시킬 때 기회 되면 시도해보겠습니다.
💬 리뷰 요구 사항
=> [Feature] implement Best BoardPost

src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/resources/static/js/boards/bestPost.js, src/main/resources/static/js/boards/board.js, src/main/resources/static/js/boards/post.js
💡 연관된 이슈
close #137 
📝 작업 내용
- 게시판 제목 글자수 20글자 제한
- 게시글 제목 글자수 10글자 제한
- 베스트 게시글 글자수 20글자 제한
💬 리뷰 요구 사항
=> [Feature] improvement of community part character limitation 

src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/response/BoardPostCommentResponse.java, src/main/java/like/lion/way/board/application/response/BoardPostDetailResponse.java, src/main/java/like/lion/way/board/application/response/BoardPostResponse.java, src/main/java/like/lion/way/board/application/response/BoardPostScrapsResponse.java, src/main/java/like/lion/way/user/controller/restcontroller/UserRestController.java, src/main/java/like/lion/way/user/repository/UserRepository.java, src/main/java/like/lion/way/user/service/UserService.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java, src/main/resources/static/js/boards/post.js, src/main/resources/static/js/boards/postDetail.js, src/main/resources/static/js/boards/scrap.js
close #139 
기존에 nickname을 클릭했을 때, 서버에서 nickname으로 username을 반환하는 로직이었는데, nickname을 띄울 때 담기는 response에 username을 내포해서 response하게 수정했습니다.
=> [BugFix] fix user feed movement logic

src/main/java/like/lion/way/board/api/BoardRestController.java, src/main/java/like/lion/way/board/api/request/BoardSearchRequest.java, src/main/java/like/lion/way/board/application/BoardService.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/request/BoardSearchServiceRequest.java, src/main/java/like/lion/way/board/repository/BoardPostRepository.java, src/main/java/like/lion/way/board/repository/BoardRepository.java, src/main/resources/static/js/boards/board.js, src/main/resources/static/js/boards/post.js, src/main/resources/templates/pages/boards/boardForm.html, src/main/resources/templates/pages/boards/postForm.html
close #143
제목 및 내용으로 검색할 수 있는 기능 구현했습니다.
=> [Feature] implement community serch

src/main/java/like/lion/way/ApiResponse.java, src/main/java/like/lion/way/chat/controller/rest/ChatRestController.java, src/main/java/like/lion/way/chat/controller/rest/MessageRestController.java, src/main/java/like/lion/way/chat/domain/dto/ChatCreateResultDTO.java, src/main/java/like/lion/way/chat/domain/dto/ChatFuncResultDTO.java, src/main/java/like/lion/way/chat/domain/dto/OldMessageDTO.java, src/main/resources/static/js/chat/chat-room.js, src/main/resources/static/js/chat/chat.js, src/main/resources/static/js/feed/userFeed.js
- 기존 api 응답을 ApiResponse에 맞춰서 변경
close #142
=> [Refactor] chat api response

src/main/java/like/lion/way/WayApplication.java, src/main/java/like/lion/way/chat/controller/rest/MessageRestController.java, src/main/java/like/lion/way/chat/service/impl/MessageServiceImpl.java, src/main/resources/static/js/chat/chat-room.js
- 채팅방 입장시 메세지 처리 부분으로 인해 로딩 시간이 길어짐
- 비동기 저리 해서 채팅방 입장시 로딩 시간을 줄임
=> [Refactor] Improved chat performance

src/main/java/like/lion/way/board/api/BoardRestController.java, src/main/java/like/lion/way/board/application/request/BoardPostCreateServiceRequest.java, src/main/java/like/lion/way/file/controller/FileRestController.java, src/main/java/like/lion/way/file/service/S3Service.java, src/main/java/like/lion/way/file/service/impl/S3ServiceImpl.java, src/main/resources/static/css/boards/postDetail.css, src/main/resources/static/js/boards/postCreate.js, src/main/resources/static/js/boards/postDetail.js, src/main/resources/static/js/boards/postEdit.js, src/main/resources/templates/pages/boards/postCreateForm.html, src/main/resources/templates/pages/boards/postEditForm.html
💡 연관된 이슈
close #145 
📝 작업 내용
게시글 생성/수정 시 이미지 업로드 가능하게 구현했습니다.
💬 리뷰 요구 사항
=> [Feature] board post img upload

src/main/java/like/lion/way/user/controller/restcontroller/UserRestController.java, src/main/java/like/lion/way/user/service/serviceImpl/FollowServiceImpl.java, src/main/resources/static/css/user/usersetting.css, src/main/resources/templates/pages/user/followSetting.html
- 팔로워 팔로잉목록에서 해당 유저 클릭 시 그 유저 피드로 이동
- 회원탈퇴 진행했을때 쿠키 뺏기
=> feat: follower following click-> feed page And userDelete mod

src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/response/BoardTitleResponse.java, src/main/java/like/lion/way/config/SecurityConfig.java, src/main/java/like/lion/way/file/service/S3Service.java, src/main/resources/static/css/boards/board.css, src/main/resources/static/js/boards/board.js
close #155 
- board
커뮤니티 게시판 보여주기의 게시판에 대한 설명 추가
게시판명 밑에 설명 배치
=> [Feature] 커뮤니티 게시판에서 게시판 설명 추가 , 비로그인 이미지 보이게 허용 

src/main/java/like/lion/way/admin/controller/BlueCheckRestController.java, src/main/java/like/lion/way/admin/controller/adminController.java, src/main/java/like/lion/way/admin/service/BlueCheckService.java, src/main/java/like/lion/way/admin/service/Impl/BlueCheckServiceImpl.java, src/main/java/like/lion/way/feed/controller/PostController.java, src/main/java/like/lion/way/user/service/UserService.java, src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java, src/main/resources/static/js/admin/bluecheckList.js, src/main/resources/static/js/common.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/pages/admin/blueCheckList.html, src/main/resources/templates/pages/feed/userFeed.html
=> [Feature] administrator menu

src/main/java/like/lion/way/board/api/request/BoardCreateRequest.java, src/main/java/like/lion/way/board/api/request/BoardSearchRequest.java, src/main/java/like/lion/way/board/application/BoardServiceImpl.java, src/main/java/like/lion/way/board/application/request/BoardCreateServiceRequest.java, src/main/java/like/lion/way/board/application/request/BoardSearchServiceRequest.java, src/main/java/like/lion/way/board/domain/Board.java, src/main/java/like/lion/way/board/repository/BoardPostRepository.java, src/main/resources/static/js/boards/board.js, src/main/resources/static/js/boards/boardCreate.js, src/main/resources/static/js/boards/post.js, src/main/resources/templates/fragments/aside.html, src/main/resources/templates/pages/boards/boardCreateForm.html, src/main/resources/templates/pages/boards/boardForm.html
💡 연관된 이슈
close #168 
📝 작업 내용
- 게시글 검색 시 다른 게시판의 게시글도 검색되는 오류 수정
- 사이드바 수정
- board 생성 시 익명 여부 삭제
- boardForm.js 수정
💬 리뷰 요구 사항
=> [Fix] community some error fix
